version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:2.7

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependancies
          command: |
            - pip install -U platformio
            - platformio update

      - run:
          name: run tests
          command: |
            - platformio run

